global:
  resolve_timeout: 1s

route:
  receiver: web.hook
  group_by:
  - alertname
  continue: false
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 10s
receivers:
- name: web.hook
  webhook_configs:
  - send_resolved: true
    http_config:
      follow_redirects: true
    url: http://flask-app:5000
    max_alerts: 0
templates: []
